# Configuração para execução dentro do Docker Compose
# O hostname 'db' é o nome do serviço PostgreSQL definido no docker-compose.yml
spring.datasource.url=jdbc:postgresql://db:5432/pedidos_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
